stages:
#  - test
#  - build
  - deploy
#  - dast

#include:
#  - template: Dependency-Scanning.gitlab-ci.yml
#  - template: Security/License-Scanning.gitlab-ci.yml
#  - template: Security/Secret-Detection.gitlab-ci.yml
#  - template: Security/SAST.gitlab-ci.yml
#  - template: DAST.gitlab-ci.yml

#variables:
#  SAST_GOSEC_LEVEL: 2
#  DAST_WEBSITE: http://vm3714.kaj.pouta.csc.fi:30149/

build:
  stage: build
 # when: manual
  script: echo "Building"
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

deploy:
    stage: deploy
 #   when: manual
    script: echo "Deploying"
    image: bitnami/kubectl:latest
    script:
        - kubectl apply -f yaml/service.yaml
        - kubectl apply -f yaml/deployment.yaml

        - echo "http://vm3714.kaj.pouta.csc.fi:30149/"
