stages:
#- test
- build
- deploy

#include:
# - template: Dependency-Scanning.gitlab-ci.yml
#  - template: Security/License-Scanning.gitlab-ci.yml
#  - template: Security/Secret-Detection.gitlab-ci.yml
#  - template: Security/SAST.gitlab-ci.yml

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
   # - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  ## - general
  ## - master
#
#
deploy:
    stage: deploy
    #when: manual
    image: bitnami/kubectl:latest
    script:
#    - 'kubectl apply -f yaml/minio-secrets.yaml'
#    - sleep 3
#    - 'kubectl apply -f yaml/postgres-secrets.yaml'
#    - sleep 3
#    - 'kubectl apply -f yaml/backend-config.yaml'
#    - sleep 3
    - 'kubectl apply -f service.yaml'
    - sleep 3
    - 'kubectl apply -f deployment.yaml'
    - sleep 3
    - 'echo "Deployment complete"'
    
   # environment:
    #    name: Development
     #   url: https://vm3728.kaj.pouta.csc.fi:8443
