stages:
  - test

test:
  stage: test
  image: gitlab.labranet.jamk.fi:4567/wimma-lab-2019/mysticons/cayac/tools/robot
  script:
    - export ROBOT_TESTS=/sample_tests
    - export OUTPUT_DIR=/output
    - run.sh
  artifacts:
    paths:
      - DIRECTORY_TO_SAVE_OUTPUT_TO/
