# Deployment part
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todofront # Deployment name
spec:
  selector:
    matchLabels:
      app: todoback
      tier: frontend
      track: stable
  replicas: 1 # number of nodes.
  template:
    metadata:
      labels:
        app: todoback
        tier: frontend
        track: stable
    spec:
      containers:
      - name: todofront
        image: "gcr.io/wimmalab1/todofrontend" # image location
        env: # enviroment variable
          - name: BACKEND_HOSTNAME # container inbuilt variable to retrieve ip
            value: todoback # the container where to connect
---
# Service part
apiVersion: v1
kind: Service
metadata:
  name: todofront
spec:
  selector:
    app: todoback
    tier: frontend
  ports:
  - protocol: TCP
    port: 8080 
    targetPort: 8080
  type: LoadBalancer
