apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: temp
  name: temp
  namespace: default
spec:
    template:
     metadata:
       annotations:
         commit_sha: $CI_COMMIT_SHORT_SHA
spec:
  replicas: 4
  selector:
    matchLabels:
      app: temp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: temp
    spec:
      containers:
      - image: gitlab.labranet.jamk.fi:4567/wimmalab2021/pengwin/wimmalab2021-nextjs:<VERSION>
        imagePullPolicy: Always
        name: temp
