apiVersion: v1
kind: Service
metadata:
  labels:
    app: temp
  name: temp
  namespace: default
spec:
  ports:
  - nodePort: 80
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: temp
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.241
